baseURL = "https://neverfapdeluxe.com/"
title = "NeverFap Deluxe | The World's Most Comprehensive Porn Addiction Recovery Platform."
languageCode = "en-us"
theme = "deluxe_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-132863786-1"

ignoreFiles = [ "\\.notes$" ]

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  post = "/articles/:slug"

[author]
  name = "Julius Reade"

[markup.goldmark.renderer]
  unsafe= true

# [outputs]
#   page = ["json", "html"] # A player
#   section = ["json", "html"] # All players
#   home = ["json", "html"] # Everything

# [mediaTypes]
#   [mediaTypes."application/json"]
#     suffixes = [ "json" ]
#   [mediaTypes."text/html"]
#     suffixes = [ "html" ]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]
  page = ["HTML", "JSON"]
